name: healthcare_app
description: "SignCare - AI 기반 개인 맞춤형 헬스케어 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: 14.8.1
  
  # Local Database
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Network
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  web_socket_channel: ^3.0.3
  
  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  
  # UI/UX
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  
  # Charts and Data Visualization
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^29.2.10
  
  # Health & Sensors
  health: ^13.1.0
  permission_handler: ^12.0.0+1
  
  # Camera & Image
  camera: ^0.11.1
  image_picker: ^1.1.2
  image: ^4.2.0
  
  # ML/AI
  tflite_flutter: ^0.11.0
  
  # Social Login
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  
  # Weather API
  http: ^1.2.2
  geolocator: ^14.0.1
  
  # OCR and Text Recognition
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_barcode_scanning: ^0.14.1
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  uuid: ^4.4.2
  
  # Logging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.2.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/
    - assets/lottie/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

